# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'FontingAwesome' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FontingAwesome
    pod 'FontAwesomeKit', '~> 2.2'
    pod 'CWStatusBarNotification', '~> 2.3'

  target 'FontingAwesomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FontingAwesomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
